---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: microservice
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: backend
     spec:
       containers:
         - name: server
           image: nginx
           ports:
             - containerPort: 80
         - name: prometheus
           image: prom/prometheus:latest
           ports:
             - containerPort: 9090
